<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <Target Name="ILRepacker" AfterTargets="Build">
        <ItemGroup>
            <InputAssemblies Include="$(TargetPath)" />
            <InputAssemblies Include="$(ServerSync)" />
            <ILRepackLibs Include="$(OutputPath)" />
            <ILRepackLibs Include="$(GameManagedPath)" />
            <ILRepackLibs Include="$(BepInExCore)" />
        </ItemGroup>
        <ILRepack Parallel="true"
                DebugInfo="false"
                Internalize="true"
                InputAssemblies="@(InputAssemblies)"
                OutputFile="$(TargetPath)"
                TargetKind="Dll"
                LibraryPath="@(ILRepackLibs)" />
    </Target>
</Project>
