[config]
schemaVersion = "0.0.1"

[package]
namespace = "eoger"
name = "BuildResourceRequirements_Updated"
versionNumber = "1.2.1"
description = "Configurable build resource requirements per build category. Fork of Jammerbam's mod, updated for Valheim 1.0."
websiteUrl = "https://github.com/eoger/BuildResourceRequirements"
containsNsfwContent = false
[package.dependencies]
denikson-BepInExPack_Valheim = "5.4.2350"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./bin/Release/BuildResourcesMod.dll"
target = "BuildResourcesMod.dll"

[[build.copy]]
source = "./CHANGELOG.md"
target = "CHANGELOG.md"

[[build.copy]]
source = "./LICENSE"
target = "LICENSE"

[publish]
repository = "https://thunderstore.io"
communities = [ "valheim", ]
[publish.categories]
valheim = [ "mods", "building", "server-side", "client-side", ]
